apiVersion: v1
kind: Service
metadata:
  name: ai-search-engine-service
spec:
  selector:
    app: ai-search-engine
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 8002 
  type: LoadBalancer   